export const namesWithId = {
  1: "Ajay Admin",
  2: "Guest",
  3: "Jatin Nagpal",
  4: "Rajveer Rajwat",
  5: "Ankit Srivastava",
  6: "Ram Prakash",
  7: "Hemilton",
  8: "Piyush",
  9: "Margoob",
  10: "Adesh Gupta",
  11: "Farooque Reza",
  12: "Yashika Gualati",
  13: "Amar Gupta",
  14: "Ajay Pant",
  15: "Saurabh Bhatnagar",
  16: "Rahul",
  17: "Anuj Gupta",
  18: "Saurabh Mishra",
  19: "Vinay Kumar Srivastava",
  20: "Mayank kr Singh",
  21: "Gaurav Kumar",
  22: "Vivek Singh",
  23: "Raghavendra",
  24: "Nitin Kumar Pal",
  25: "InduKant Kumar",
  26: "Shiva Raj Pacha",
  27: "Atul Sungdha",
  28: "Menna Shrama",
  29: "Vikash Kumar",
  30: "Sachin Yadav",
  31: "Akshay Baliyan",
  32: "Mayank",
  33: "Jaswant",
  34: "Ravinder Kumar Yadav",
  35: "Pragati Prajapati",
  36: "Kashika",
  37: "Dinesh Lohmor",
  38: "Rahul Panwar",
  39: "Navtej",
  40: "Ankur Thakral",
  42: "Rupak",
  43: "Arun Kumar l1",
  44: "Jitender Kumar l1",
  45: "Mohan Kumar",
};
